---
title: "git_00"
author: "Daniel Esteves"
date: "Summer 2024"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Build a Poem with a sequence of commits to the master branch.
Our project will be done using several commits to the master branch.
<!-- Do not modify or change any text in "!--" bracketed areas such as this --- these are instructions to
you, if you change any of this the git program will notice it and compromise your git merging strategy !-->

## First Verse 
<!--Put the first five lines of a poem by Lewis Carrol in this section!-->

The sun was shining on the sea,  
      Shining with all his might:  
He did his very best to make  
      The billows smooth and bright —  
And this was odd, because it was  
      The middle of the night  

## Second Verse
<!--Put the first five lines of a poem by Robert Frost here!-->

Before man came to blow it right  
     The wind once blew itself untaught,  
And did its loudest day and night  
     In any rough place where it caught.  

## Third Verse
<!--Put the first two verses of The Walrus and the Carpenter here!-->

The sun was shining on the sea,  
      Shining with all his might:  
He did his very best to make  
      The billows smooth and bright —  
And this was odd, because it was  
      The middle of the night. 
      
## Last Verse
<!--Put a short poem of your choice 8-20 lines,here!-->

I don’t know who needs to hear this  
other than me, but the moon will never leave  
you, you are good enough for the moon  
and the moon is good enough for you,  
because you are here and the moon is there  
every time the moon is supposed to be  
there, and isn’t it interesting when we want  
to show up for each other we say we are  
counting on it and what else but numbers  
teach us we are each one, and what else  
but the moon teaches us we are each many,  
so when you try counting  your remaining  
moments with the moon, the moon  
that will never, ever leave you, give up.  



